### ISSUE TITLE
PatoolError: patool can not unpack & not found patool

### ISSUE THREAD

**Issue by pp8372** [ponty/pyunpack#11]
Hi,

I want to use pyunpack to try to unzip cabinet file.
Code is as following:

`from pyunpack import Archive`
`sys.executable = r"C:\Users\<myname>\AppData\Local\Continuum\anaconda3\python.exe"`
`Archive("folder1//A.cab").extractall("folder1")`

Here is the traceback:

`Traceback (most recent call last):`

  `File "c:\users\<myname>\documents\repo\<programA>\test.py", line 70, in <module>`
    `Archive("folder1//Alienware_Desktop_064C.cab").extractall("folder1")`

  `File "C:\Users\<myname>\AppData\Local\Continuum\anaconda3\lib\site-packages\pyunpack\__init__.py", line 94, in extractall`
    `self.extractall_patool(directory, patool_path)`

  `File "C:\Users\<myname>\AppData\Local\Continuum\anaconda3\lib\site-packages\pyunpack\__init__.py", line 65, in extractall_patool`
    `raise PatoolError("patool can not unpack\n" + str(p.stderr))`

`PatoolError: patool can not unpack`
  `File "C:\Users\<myname>\AppData\Local\Continuum\anaconda3\Scripts\patool.exe", line 1`
`SyntaxError: Non-UTF-8 code starting with '\x90' in file C:\Users\<myname>\AppData\Local\Continuum\anaconda3\Scripts\patool.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

I am try to extract **folder1//A.cab** but the pyunpack tries to extract **patool.exe**

And the other issue is that I found in `__init__.py` for pyunpack , in line **48**, it should be
`patool_path = _exepath("patool.exe")`
or there will be an error: 
`ValueError: patool not found! Please install patool!`
even if I have already installed patool.

Environment:

Win10
spyder4.1.4
patool-1.12
pyunpack 0.2.1

**Comment by ponty** [comment]
I tried your use case on Win10 without error :
```py
from pyunpack import Archive
Archive("folder1//A.cab").extractall("folder1")
```
I repeated this test  also with Spyder in Anaconda environment without error .

`sys.executable` should not be set, if it has a wrong value then send a report.

There is no `patool.exe`, check it on download page: https://pypi.org/project/patool/#files

The error message gives you the solution: `Please install patool!`
Installing patool with pip: `pip install patool`
