### ISSUE TITLE
Unable to extract *.tar.xz in Windows

### ISSUE THREAD

**Issue by yihuajack** [ponty/pyunpack#12]
OS version: Windows 10 20H2
Python version: Python 3.9.5 and Anaconda3 2021.5 Python 3.8.8 64-bit
Requirement `patool-1,12` already satisfied
MWE:
```
import os
import sys
from pyunpack import Archive
path_to_file = 'xxx'
target_dir = 'xxx'
Archive(path_to_file).extractall(target_dir)
```
Problem: the program just hangs at the last line, not extracting the compressed files. The format of the compressed file is *.tar.xz, which is just 69350 KiB.

**Comment by ponty** [comment]
This is just a wrapper lib. Try to call patool directly:
```
patool extract xxx..tar.xz
```
