### ISSUE TITLE
Calling patool directly

### ISSUE THREAD

**Issue by miAndreev** [ponty/pyunpack#17]
Hi,
I saw that patool isn't called from python. Is there a reason to call it in a sub process?
I can provide a pull request.

**Comment by ponty** [comment]
Reasons:
1. Historic: `patool` had only CLI interface in the past.
2. License: This lib is BSD, but `patool` has GPLv3 license: https://github.com/wummel/patool/blob/master/COPYING
If we add the direct Python call, then `pyunpack` can not be used in non GPL projects as it is now.
