### ISSUE TITLE
Fails to Identify `patool` Path on Some Windows Versions

### ISSUE THREAD

**Issue by engineerjoe440** [ponty/pyunpack#20]
It seems that there's a failure in `_exepath` that doesn't allow it to correctly identify `patool.exe` on a Windows system. Seems like that could be corrected with the following (or similar) addition:

```diff
def _exepath(cmd: str) -> Optional[str]:
    for p in os.environ["PATH"].split(os.pathsep):
        fullp = os.path.join(p, cmd)
        if os.access(fullp, os.X_OK):
            return fullp
+        if os.access(fullp + ".exe", os.X_OK):
+            return fullp + ".exe"
    return None
```

**Comment by ponty** [comment]
Thanks!

**Comment by dzeron** [comment]
> Thanks!
@ponty, @eisene 
Hello! Could you please update the version in pyunpack-0.3-py2.py3-none-any.whl. There is still an old _ init _ with this error.
