### ISSUE TITLE
ImportError: No module named patoolib

### ISSUE THREAD

**Issue by viniciusbig** [ponty/pyunpack#3]
Hello,
I'm trying to use the pyunpack to open a RAR file.

I've install the patool in order to add RAR suport (patool 1.12)
My pyunpack package is v.0.0.3

But using:

```
>>> from pyunpack import Archive
>>> Archive('my-file.rar').extractall('./')
```

I get the error: `ImportError: No module named patoolib`

I'm using Python 2.7 and a Mac OS El Capitan

What i'm missing?
Thanks for any help

**Comment by ponty** [comment]
I have no Mac, but it works on Ubuntu.
I just installed it with pip on a clean ubuntu trusty version:
```
pip install patoolib
pip install pyunpack
```

Your installation of patoolib can be wrong. Try this in python:
```python
import patoolib
```

**Comment by ponty** [comment]
Please try the latest version!

**Comment by ponty** [comment]
Maybe install error

**Comment by oubihis** [comment]
for "import patoolib"
you need install "pip install patool"
